### ISSUE TITLE
Deploy Project Using Docker and Azure

### ISSUE THREAD

**Issue by sharara6** [nour-awad/tech-hub#14]
As part of the project deployment process, we need to set up and deploy the application using Docker containers on the Azure platform.

#### Tasks:

- [x] 1.  Set up Docker configuration for the project.
- [x] 2.  Create Docker images for the application components.
- [x] 3.  Create Azure resources (e.g., Azure Container Registry, Azure Kubernetes Service) for deployment.
- [ ] 4.  Configure deployment pipelines for seamless deployment using Azure DevOps or a similar tool.

#### Estimated Duration: 

- 2 Days
