### ISSUE TITLE
Shopping Cart Functionality Implementation

### ISSUE THREAD

**Issue by nour-awad** [nour-awad/tech-hub#7]
As a customer, I want the ability to add products to a shopping cart and manage my selected items.

**Tasks:**

- [x] 1. **Implement "Add to Cart" Button:**
Add an "Add to Cart" button on product pages for logged-in users.

- [x] 2. **Enable Adding and Removing Products from Cart:**
Implement functionality that allows users to add and remove products from their shopping cart.

- [x] 3. **Implement View and Manage Cart:**
Create options for users to view and manage the entire shopping cart easily.

**Estimated Duration:**
- 4 days
